module.exports.userList=[
	{ arrayId: 0,
    prename: 'NoPreName',
    lastname: 'NoLastName',
    companyId: 'NoCompanyId',
    image: 'http://data.whicdn.com/images/291787628/large.jpg',
    tags: {idrows: ['']}  },
	{ arrayId: 1,
    prename: 'hans-peter',
    lastname: 'targaryen',
    companyId: 'b-5',
    image: 'http://data.whicdn.com/images/291787628/large.jpg',
    tags: {idrows: ['testTag']}  },
  { arrayId: 2,
    prename: 'peter',
    lastname: 'arry',
    companyId: 'a-11',
    image: 'http://data.whicdn.com/images/29178762/large.jpg',
    tags: {idrows: ['testTag']}  },
  { arrayId: 3,
    prename: 'hans',
    lastname: 'arry',
    companyId: 'k-98',
    image: 'http://data.whicdn.com/images/291787665/large.jpg',
    tags: {idrows: ['testTag']}  },
  { arrayId: 4,
    prename: 'robert',
    lastname: 'greyjoy',
    companyId: 'b-5',
    image: 'http://data.whicdn.com/images/291787644/large.jpg',
    tags: {idrows: ['testTag']}  },
  { arrayId: 5,
    prename: 'robert',
    lastname: 'thorn',
    companyId: 'grk-52',
    image: 'http://data.whicdn.com/images/291787636/large.jpg',
    tags: {idrows: ['testTag']}  },
  { arrayId: 6,
    prename: 'sebastian',
    lastname: 'greyjoy',
    companyId: 'ak-25',
    image: 'http://data.whicdn.com/images/291787632/large.jpg',
    tags: {idrows: ['testTag']}  },
  { arrayId: 7,
    prename: 'basti',
    lastname: 'tully',
    companyId: 'b-5',
    image: 'http://data.whicdn.com/images/291787645/large.jpg',
    tags: {idrows: ['testTag']}  },
  { arrayId: 8,
    prename: 'bastian',
    lastname: 'baratheon',
    companyId: 'a-1',
    image: 'http://data.whicdn.com/images/291787614/large.jpg',
    tags: {idrows: ['testTag']}  },
  { arrayId: 9,
    prename: 'hans joachim',
    lastname: 'greyjoy',
    companyId: 'grk-52',
    image: 'http://data.whicdn.com/images/291787628/large.jpg',
    tags: {idrows: ['testTag']}  },
  { arrayId: 10,
    prename: 'peter',
    lastname: 'frey',
    companyId: 'c-2',
    image: 'http://data.whicdn.com/images/291787631/large.jpg' ,
    tags: {idrows: ['testTag']}  } ];
